//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recuersos_Humanos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salida
    {
        public int ID { get; set; }
        public Nullable<int> FK_Empleado { get; set; }
        public string Tipo_Salida { get; set; }
        public string Motivo { get; set; }
        public string Dia { get; set; }
        public string Mes { get; set; }
        public string Año { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
